const productsData = [
  {
    name: "WEB-ITM-0015",
    creation: "2023-08-25 12:29:50.467399",
    modified: "2023-08-25 12:29:50.467399",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    idx: 0,
    naming_series: "WEB-ITM-.####",
    web_item_name:
      'Digital Media Touchscreen Receiver Android 9.0 With Bluetooth, GPS And 6.9" IPS Display',
    route:
      "products/sound-and-multimedia/digital-media-touchscreen-receiver-android-90-with-bluetooth-gps-and-69-ips-display-opwwh",
    has_variants: 0,
    variant_of: null,
    published: 1,
    item_code: "AD-6800",
    item_name:
      'Digital Media Touchscreen Receiver Android 9.0 With Bluetooth, GPS And 6.9" IPS Display',
    item_group: "Sound and Multimedia",
    stock_uom: "Nos",
    description:
      'Operating system: Android 10.\nMaximum output power: 4x50W.\n6.9" IPS display with capacitive touchscreen.\nDisplay resolution: 1024×600px.\nProcessor: Cortex A7, 1.3 GHz, 4 cores.\nRAM: 2GB. ROM: 16GB.\nBuilt-in GPS/GLONASS module with external antenna.\nBuilt-in WI-FI and Bluetooth.\nFM radio tuner with 30 station memory.\nSupport for USB interfaces.\nAV input for external sources.\nVideo formats: MKV, MOV, AVI, MP4.\nAudio formats: MP3, WMA, AAC, WAV, FLAC.\n12 band equalizer.\nRear view camera input.\nFront camera input.  ',
    brand: "ACV",
    website_image: "/files/AD-6800.png",
    website_image_alt: null,
    slideshow: null,
    thumbnail: "/files/AD-6800_small.png",
    website_warehouse: null,
    on_backorder: 0,
    short_description: null,
    web_long_description: null,
    show_tabbed_section: 0,
    ranking: 0,
    website_content: null,
    _user_tags: null,
    _comments: null,
    _assign: null,
    _liked_by: null,
  },
  {
    name: "WEB-ITM-0016",
    creation: "2023-08-25 12:29:55.721935",
    modified: "2023-08-25 12:29:55.721935",
    modified_by: "Administrator",
    owner: "Administrator",
    docstatus: 0,
    idx: 0,
    naming_series: "WEB-ITM-.####",
    web_item_name:
      'Digital Media Touchscreen Receiver With Bluetooth, 6.9" LCD Display',
    route:
      "products/sound-and-multimedia/digital-media-touchscreen-receiver-with-bluetooth-69-lcd-display-d16jc",
    has_variants: 0,
    variant_of: null,
    published: 1,
    item_code: "WD-6920/6930",
    item_name:
      'Digital Media Touchscreen Receiver With Bluetooth, 6.9" LCD Display',
    item_group: "Sound and Multimedia",
    stock_uom: "Nos",
    description:
      'Operating system: WinCE.\nMaximum output power: 4x50W.\n6.9" LCD display with capacitive touchscreen.\nDisplay resolution: 1024×600px.\nCPU: C200S.\nFM/OIRT radio tuner with 18 ɓation memory.\nBluetooth 4.0.\nPhoneLink app for smaɒphones.\nSupport for USB, microSD intefaces.\n12 RCA: AV input for external sources, Subwoofer, RCA video output.\nVideo formats: MKV, MOV, AVI, MP4.\nAudio formats: MP3, WMA, AAC, WAV, FLAC.\nEqualizer: 5 presets Pop, Classic, Rock, Jazz, Drums.\nRear view camera input.\nMulticolor backlighting of buttons.',
    brand: "ACV",
    website_image: "/files/WD-6920-6930.png",
    website_image_alt: null,
    slideshow: null,
    thumbnail: "/files/WD-6920-6930_small.png",
    website_warehouse: null,
    on_backorder: 0,
    short_description: null,
    web_long_description: null,
    show_tabbed_section: 0,
    ranking: 0,
    website_content: null,
    _user_tags: null,
    _comments: null,
    _assign: null,
    _liked_by: null,
  },
];
export default productsData;
